fix install shell

diff --git a/.github/workflows/debug-install-shell.yml b/.github/workflows/debug-install-shell.yml
--- a/.github/workflows/debug-install-shell.yml
+++ b/.github/workflows/debug-install-shell.yml
@@ -47,8 +47,8 @@ jobs:
         run: |
           chmod +x install.sh
           ./install.sh --install-dir "~/.snm-demo"
-          # if [ ! -d ~/.snm-demo ]; then
-          #   echo "Error: ~/.snm-demo directory not found!"
-          #   exit 1
-          # fi
+          if [ ! -d ~/.snm-demo ]; then
+            echo "Error: ~/.snm-demo directory not found!"
+            exit 1
+          fi
           ls -l ~/.snm-demo
