test install shell

diff --git a/.github/workflows/debug-install-shell.yml b/.github/workflows/debug-install-shell.yml
--- a/.github/workflows/debug-install-shell.yml
+++ b/.github/workflows/debug-install-shell.yml
@@ -42,5 +42,13 @@ jobs:
             exit 1
           fi
           ls -l ~/.snm
-        env:
-          RUST_BACKTRACE: full
+
+      - name: Test install with install-dir
+        run: |
+          chmod +x install.sh
+          ./install.sh --install-dir "./.snm-demo"
+          if [ ! -d ~/.snm-demo ]; then
+            echo "Error: ~/.snm-demo directory not found!"
+            exit 1
+          fi
+          ls -l ~/.snm-demo
